version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crew_ai_studio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./crew_ai_studio.db}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8080}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8000}
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  postgres_data:
